# Generated by Django 5.0.14 on 2026-07-07 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'История поиска',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_history', to='listings.listing', verbose_name='Объявление')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История просмотра',
                'verbose_name_plural': 'История просмотров',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
