# Generated by Django 5.0.14 on 2026-07-09 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('listings', '0003_alter_listing_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='viewhistory',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='unique_listing_view'),
        ),
    ]
