# Generated by Django 5.0.14 on 2026-07-07 20:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена за месяц (EUR)')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('housing_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('studio', 'Студия'), ('room', 'Комната')], default='apartment', max_length=20, verbose_name='Тип жилья')),
                ('city', models.CharField(max_length=100, verbose_name='Город (Германия)')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Арендодатель')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'), models.Index(fields=['rooms'], name='listings_li_rooms_4641e1_idx'), models.Index(fields=['city'], name='listings_li_city_e45c53_idx'), models.Index(fields=['is_active'], name='listings_li_is_acti_03d721_idx')],
            },
        ),
    ]
