# Generated by Django 5.0.14 on 2026-07-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Owner',
            new_name='owner',
        ),
    ]
