# Generated by Django 5.0.14 on 2026-07-09 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
        ('listings', '0003_alter_listing_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('tenant', 'listing', 'start_date', 'end_date'), name='unique_booking'),
        ),
    ]
