# Generated by Django 5.0.14 on 2026-07-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_tenant'),
        ('listings', '0003_alter_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='listings.listing', verbose_name='Объявление'),
        ),
    ]
